### ISSUE TITLE
Rcpp memory not mapped errors in builds

### ISSUE THREAD

**Issue by linanqiu** [forestry-labs/Rforestry#19]
@theo-s this is the error you wanted me to look at right?

**Comment by theo-s** [comment]
Hi Linan,

Sorry for the confusion, this error was due to me prematurely pushing some development code to master. It should not be a problem now. 

The main thing I was hoping to add was for us to run `R CMD check --use-valgrind` in a docker container on pushes to master. Basically we have had some errors in the past where normal checks are okay, but when CRAN runs checks with valgrind, we get some warnings.

When I solved this problem manually, I had to run checks with both:

https://hub.docker.com/r/krlmlr/r-debug

and 

https://hub.docker.com/r/rocker/r-devel-ubsan-clang
