### ISSUE TITLE
forestry function not found

### ISSUE THREAD

**Issue by romainpirracchio** [forestry-labs/Rforestry#2]
Trying to test the package. Despite proper download & install, I keep on getting the [could not find function "forestry"] error message. Thanks !

**Comment by theo-s** [comment]
Sorry that this happens, I will check out this error. Just to clarify, this is after installing the package and loading with `library(Rforestry)`, then the function is not showing up?

**Comment by romainpirracchio** [comment]
My bad. I was using :
remotes::install_github("soerenkuenzel/forestry »)

Now it is working.
I am also trying to use causalToolbox (remotes::install_github("soerenkuenzel/causalToolbox »)) and I’m getting the following error message:
Error: 'forestry' is not an exported object from 'namespace:forestry'

Thanks !
Romain 


=============================
Prof. Romain Pirracchio, MD MPH PhD

Ronald D Miller Distinguished Professor of Anesthesia and Perioperative Medicine
Professor of Anesthesia and Critical Care Medicine
Professor of Biostatistics

**Comment by theo-s** [comment]
Great, I'm glad this first problem was fixed! In order to use the `causalToolbox` package, we are currently migrating that package to the forestry-labs team as well, I realize our installation directions were outdated, so I have updated these now. 

In order to install the new version of  `causalToolbox`, which should be compatible, you should use `remotes::install_github("forestry-labs/causalToolbox")`, this should get the version from forestry-labs which uses the new version of Rforestry

Let me know if there is anything further I can do to help.
